@echo off
(
echo Initializing Git...
git init
echo Adding remote...
git remote add origin https://github.com/RishiNarayan1/Ecentra-2k26.git
echo Fetching...
git fetch origin
echo Checking out main...
git checkout main
echo Removing zip...
git rm "New One.zip"
echo Committing...
git commit -m "Remove zip file"
echo Pushing...
git push origin main
) > git_log.txt 2>&1
